apiVersion: apps/v1
kind: Deployment
metadata:
  name: hieuhuynh-project-capstone
  labels:
    app: hieuhuynh-project-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hieuhuynh-project-capstone
  template:
    metadata:
      labels:
        app: hieuhuynh-project-capstone
    spec:
      containers:
        - name: hieuhuynh-project-capstone
          image: trunghieu9506/hieuhuynh-project-capstone:latest
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 80
