apiVersion: v1
kind: Service
metadata:
  name: hieuhuynh-project-capstone-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      name: hieuhuynh-project-capstone
      protocol: TCP
  selector:
    app: hieuhuynh-project-capstone